### ISSUE TITLE
NOT POINTING ON CORRECT WINNING ON INDEX

### ISSUE THREAD

**Issue by jayandradeph** [IvanAdmaers/react-roulette-pro#24]
Hello, good day. Thank you so much for making this cool project.

I do have encounter an issue when it is built in **PRODUCTION** or when it is **DEPLOYED**. In my local machine it is working fine, no issues, but when it is deployed it is not pointing on the correct wining index. When I checked the console log, no errors found also.

I tried to change the view from desktop into a mobile view, it fixed the issue, and when I switched it back to desktop view, it also fixed the issue but it should not be like this, right? I don't if this is only a css issue or what.

[Please see video](https://streamable.com/y6fzsl)

**Comment by IvanAdmaers** [comment]
Hello. Please check the _prizeIndex_ prop. Make sure it sets a correct prize item index.

**Comment by jayandradeph** [comment]
Yes I have set it correctly. I did add some logs also just to check if the prizeIndex was right, and it is right. 
I tried this scenario, I have set the prizeIndex to 5 for both local and production, and I noticed that they have different inline style on the  <ul> tag, local is left:503.5px, production is left: -1127.5.px


I really appreciate that you reply on my issue.

**Comment by IvanAdmaers** [comment]
Got you. Can I take a look on your production site? You may just send a link to it. I need it because first I gotta reproduce this issue to say anything about it.On 20 Feb 2023, at 9:07 p.m., Jay Andrade ***@***.***> wrote:﻿
Yes I have set it correctly. I did add some logs also just to check if the prizeIndex was right, and it is right.
I tried this scenario, I have set the prizeIndex to 5 for both local and production, and I noticed that they have different inline style on the   tag, local is left:503.5, production is 1127.5.

**Comment by IvanAdmaers** [comment]
And also it’d be amazing if you provide your component where described the roulette logic. This is the most important part.On 20 Feb 2023, at 9:07 p.m., Jay Andrade ***@***.***> wrote:﻿
Yes I have set it correctly. I did add some logs also just to check if the prizeIndex was right, and it is right.
I tried this scenario, I have set the prizeIndex to 5 for both local and production, and I noticed that they have different inline style on the   tag, local is left:503.5, production is 1127.5.

**Comment by jayandradeph** [comment]
I think I know now why it has a different inline style left prizeindex offset. I am using tab panels, so upon loading the page, it (RoulettePro) will be rendered, but it is hidden since it is not the default, so the width is different. I have replicated it now on my local machine. I selected another default tab panel and then reloaded the page, and when I selected that panel with the Roulette Pro and clicked the spin button, it had a different width, not the same as the default tab panel with the Roulette Pro in it.

So what I am going to do now is make it re-render every time I select this tab with Roulette Pro.

![image](https://user-images.githubusercontent.com/104615591/220245827-3c03d686-8976-4d15-938c-d48ad69e20a2.png)

**Comment by jayandradeph** [comment]
This issue is now resolved. 
For those developers who will be facing this kind of issue when implementing it on a tab panels, you can fix it by applying the lazy loading principle. Just load the component when it is really needed.

**Comment by IvanAdmaers** [comment]
Good job 👍You’re a master. Feel free to open a new issue if you have any questions. Have a good one.On 21 Feb 2023, at 2:58 a.m., Jay Andrade ***@***.***> wrote:﻿
Closed #24 as completed.

**Comment by mance819** [comment]
Me and a friend had same issue and its still in the open issues(fixed it so he should close it later) for us the roulete was off by 200-300px when it first rendered. then if we moved the tab width or height ever so slightly it would re-render and fix it self and work perfectly after that. For us the problem was in the css. I still dont know what triggered it but we just rolled back and it works now
